server:
    port: 9080
spring:
    datasource:
        password: '#include<winuser.h>'
        url: jdbc:mysql://localhost:3306/moneybadger?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: create
